server:
  port: 8084

spring:
  application:
    name: notification-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/notification_db?serverTimezone=Asia/Kolkata}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 465
    username: thebigb5602@gmail.com
    password: ksqs cufk ayzq bvet

    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true


  jpa:
    hibernate:
      ddl-auto: update   # or create-drop for first-time dev
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-group-v2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.CharlesRiverDevelopment.notification_service.dto.LoanApprovedEvent
        spring.json.use.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info