services:
  postgres:
    image: postgres:15
    container_name: loan_payment_postgres
    restart: always
    environment:
      POSTGRES_DB: loan_payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      TZ: Asia/Kolkata        # Correct timezone
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
