
CREATE TABLE public.kyc (
    id bigint NOT NULL,
    document_type character varying(255),
    document_url character varying(255),
    uploaded_at timestamp(6) without time zone,
    verification_status character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT kyc_verification_status_check CHECK (((verification_status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- TOC entry 215 (class 1259 OID 16385)
-- Name: kyc_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kyc ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kyc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16395)
-- Name: loan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.loan (
    id bigint NOT NULL,
    end_date timestamp(6) without time zone,
    is_active boolean,
    monthly_payment double precision,
    principal_amount double precision,
    start_date timestamp(6) without time zone,
    total_payment double precision,
    loan_app_id bigint NOT NULL
);


--
-- TOC entry 220 (class 1259 OID 16401)
-- Name: loan_application; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.loan_application (
    id bigint NOT NULL,
    amount double precision,
    reason character varying(255),
    application_date timestamp(6) without time zone,
    approval_date timestamp(6) without time zone,
    interest_rate double precision,
    status character varying(255),
    term_months bigint,
    user_id bigint NOT NULL,
    CONSTRAINT loan_application_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- TOC entry 219 (class 1259 OID 16400)
-- Name: loan_application_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.loan_application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loan_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16394)
-- Name: loan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.loan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16410)
-- Name: loan_status_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.loan_status_history (
    id bigint NOT NULL,
    remarks character varying(255),
    status character varying(255),
    updated_at timestamp(6) without time zone,
    loan_app_id bigint NOT NULL,
    CONSTRAINT loan_status_history_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])))
);



--
-- TOC entry 221 (class 1259 OID 16409)
-- Name: loan_status_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.loan_status_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loan_status_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16419)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255),
    phone_number character varying(255),
    username character varying(255)
);

--
-- TOC entry 223 (class 1259 OID 16418)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3288 (class 2606 OID 16393)
-- Name: kyc kyc_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kyc
    ADD CONSTRAINT kyc_pkey PRIMARY KEY (id);


--
-- TOC entry 3294 (class 2606 OID 16408)
-- Name: loan_application loan_application_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loan_application
    ADD CONSTRAINT loan_application_pkey PRIMARY KEY (id);


--
-- TOC entry 3290 (class 2606 OID 16399)
-- Name: loan loan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT loan_pkey PRIMARY KEY (id);


--
-- TOC entry 3296 (class 2606 OID 16417)
-- Name: loan_status_history loan_status_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loan_status_history
    ADD CONSTRAINT loan_status_history_pkey PRIMARY KEY (id);


--
-- TOC entry 3292 (class 2606 OID 16427)
-- Name: loan ukg60eo6oefbks42uyfciv3421t; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT ukg60eo6oefbks42uyfciv3421t UNIQUE (loan_app_id);


--
-- TOC entry 3298 (class 2606 OID 16429)
-- Name: loan_status_history uki1dwmrxpkdxtwcwaog1etu5wg; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loan_status_history
    ADD CONSTRAINT uki1dwmrxpkdxtwcwaog1etu5wg UNIQUE (loan_app_id);


--
-- TOC entry 3300 (class 2606 OID 16425)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3304 (class 2606 OID 16445)
-- Name: loan_status_history fka8nrn9f381uoth9tele3idxq3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loan_status_history
    ADD CONSTRAINT fka8nrn9f381uoth9tele3idxq3 FOREIGN KEY (loan_app_id) REFERENCES public.loan_application(id);


--
-- TOC entry 3303 (class 2606 OID 16440)
-- Name: loan_application fkejcvlj6ab0mukole0gskdttrn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loan_application
    ADD CONSTRAINT fkejcvlj6ab0mukole0gskdttrn FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3302 (class 2606 OID 16435)
-- Name: loan fkg0mnoptsn8y5fl4eb4sfk72vx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loan
    ADD CONSTRAINT fkg0mnoptsn8y5fl4eb4sfk72vx FOREIGN KEY (loan_app_id) REFERENCES public.loan_application(id);


--
-- TOC entry 3301 (class 2606 OID 16430)
-- Name: kyc fkgyumglm9oxy48p621c4ekkolp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kyc
    ADD CONSTRAINT fkgyumglm9oxy48p621c4ekkolp FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2025-09-21 15:27:06

--
-- PostgreSQL database dump complete
--

